USE DATABASE prod_games;
USE SCHEMA arcade;
USE warehouse wh_default;

-- How many achievements do players complete overall (grouped in increments of 10%)?
SELECT 
    num_achievements
    ,COUNT(DISTINCT userid) AS num_users
FROM (SELECT DISTINCT
        userid
        ,COUNT(DISTINCT achievement_name) AS num_achievements
      FROM prod_games.arcade.achievement
      WHERE achievement_name IS NOT NULL
      AND (achievement_name != 'Hey, Grizz!'
           AND achievement_name != 'Greetings, Ice Bear!'
           AND achievement_name != 'Hello, Panda!'
           AND achievement_name != 'No More Boxes'
           AND achievement_name != 'Adventurer Supreme'
           AND achievement_name != 'Tag Teamer'
           AND achievement_name != 'Point Monger'
           AND achievement_name != 'Rockin’ It'
           AND achievement_name != '3x Combo'
           AND achievement_name != 'Spring-time!'
           AND achievement_name != 'Combo Win'
           AND achievement_name != 'Close Call'
           AND achievement_name != 'Frozen Jelly bomb'
           AND achievement_name != 'High Score'
           AND achievement_name != 'Max Out Badgerclops'
           AND achievement_name != 'Max Out Adorabat'
           AND achievement_name != 'Summon Charlene'
           AND achievement_name != 'Unlock Special Powers'
           AND achievement_name != 'Aluxes Attack'
           AND achievement_name != 'High Score'
           AND achievement_name != 'Upgrade 1 Special to Max'
           AND achievement_name != 'YUMMY GUMMY'
           AND achievement_name != 'MASTER SMASHER'
           AND achievement_name != 'GOING APE'
           AND achievement_name != 'SOLD OUT'
           AND achievement_name != 'MAX POWER'
           AND achievement_name != 'Tag Everyone'
           AND achievement_name != '20x combo'
           AND achievement_name != 'Score 1k Points'
           AND achievement_name != 'Unlock All Powers'
           AND achievement_name != 'Max a power up'
           AND achievement_name != 'Gooooal!'
           AND achievement_name != 'Striker!'
           AND achievement_name != 'Kickin‘ It'
          )
      AND (game_name = 'Bottle Catch'
           OR game_name = 'Bounceback'
           OR game_name = 'Boxed Up Bears'
           OR game_name = 'Brains vs Bugs'
           OR game_name = 'Burger & Burrito'
           OR game_name = 'Camp Cardboard'
           OR game_name = 'Diamond Alliance'
           OR game_name = 'Dodge Squad'
           OR game_name = 'Fangs of Fire'
           OR game_name = 'Forever Tower'
           OR game_name = 'French Fry Frenzy'
           OR game_name = 'Galaxy Warp'
           OR game_name = 'Go Go K.O.!'
           OR game_name = 'Gumball''s Block Party'
           OR game_name = 'Jelly of the Beast'
           OR game_name = 'Kicked Out'
           OR game_name = 'Mechanoid Menace'
           OR game_name = 'Monster Kicks'
           OR game_name = 'Rainbow Wreckers'
           OR game_name = 'Rainicorn''s Flying Colors'
           OR game_name = 'Rock ''n'' Rush'
           OR game_name = 'Royal Highness'
           OR game_name = 'Rumble Bee'
           OR game_name = 'Scooby''s Knightmare'
           OR game_name = 'Shattered Dreams'
           OR game_name = 'Sick Tricks'
           OR game_name LIKE 'Smashy%'
           OR game_name = 'Squad Goals'
           OR game_name = 'Stack Tracks'
           OR game_name = 'Stellar Odyssey'
           OR game_name = 'Steven Tag'
           OR game_name = 'Teen Titans GOAL!'
           OR game_name = 'Tomb of Doom'
           OR game_name = 'Too Big to Fall'
           OR game_name = 'Xingo Mayhem'
          )
      GROUP BY 1
     )
GROUP BY 1
ORDER BY num_achievements ASC;

-- Total # of achievements a player can get: 229
SELECT DISTINCT
    COUNT(DISTINCT achievement_name) AS num_achievements
FROM prod_games.arcade.achievement
WHERE achievement_name IS NOT NULL
AND (achievement_name != 'Hey, Grizz!'
     AND achievement_name != 'Greetings, Ice Bear!'
     AND achievement_name != 'Hello, Panda!'
     AND achievement_name != 'No More Boxes'
     AND achievement_name != 'Adventurer Supreme'
     AND achievement_name != 'Tag Teamer'
     AND achievement_name != 'Point Monger'
     AND achievement_name != 'Rockin’ It'
     AND achievement_name != '3x Combo'
     AND achievement_name != 'Spring-time!'
     AND achievement_name != 'Combo Win'
     AND achievement_name != 'Close Call'
     AND achievement_name != 'Frozen Jelly bomb'
     AND achievement_name != 'High Score'
     AND achievement_name != 'Max Out Badgerclops'
     AND achievement_name != 'Max Out Adorabat'
     AND achievement_name != 'Summon Charlene'
     AND achievement_name != 'Unlock Special Powers'
     AND achievement_name != 'Aluxes Attack'
     AND achievement_name != 'High Score'
     AND achievement_name != 'Upgrade 1 Special to Max'
     AND achievement_name != 'YUMMY GUMMY'
     AND achievement_name != 'MASTER SMASHER'
     AND achievement_name != 'GOING APE'
     AND achievement_name != 'SOLD OUT'
     AND achievement_name != 'MAX POWER'
     AND achievement_name != 'Tag Everyone'
     AND achievement_name != '20x combo'
     AND achievement_name != 'Score 1k Points'
     AND achievement_name != 'Unlock All Powers'
     AND achievement_name != 'Max a power up'
     AND achievement_name != 'Gooooal!'
     AND achievement_name != 'Striker!'
     AND achievement_name != 'Kickin‘ It'
     )
AND (game_name = 'Bottle Catch'
     OR game_name = 'Bounceback'
     OR game_name = 'Boxed Up Bears'
     OR game_name = 'Brains vs Bugs'
     OR game_name = 'Burger & Burrito'
     OR game_name = 'Camp Cardboard'
     OR game_name = 'Diamond Alliance'
     OR game_name = 'Dodge Squad'
     OR game_name = 'Fangs of Fire'
     OR game_name = 'Forever Tower'
     OR game_name = 'French Fry Frenzy'
     OR game_name = 'Galaxy Warp'
     OR game_name = 'Go Go K.O.!'
     OR game_name = 'Gumball''s Block Party'
     OR game_name = 'Jelly of the Beast'
     OR game_name = 'Kicked Out'
     OR game_name = 'Mechanoid Menace'
     OR game_name = 'Monster Kicks'
     OR game_name = 'Rainbow Wreckers'
     OR game_name = 'Rainicorn''s Flying Colors'
     OR game_name = 'Rock ''n'' Rush'
     OR game_name = 'Royal Highness'
     OR game_name = 'Rumble Bee'
     OR game_name = 'Scooby''s Knightmare'
     OR game_name = 'Shattered Dreams'
     OR game_name = 'Sick Tricks'
     OR game_name LIKE 'Smashy%'
     OR game_name = 'Squad Goals'
     OR game_name = 'Stack Tracks'
     OR game_name = 'Stellar Odyssey'
     OR game_name = 'Steven Tag'
     OR game_name = 'Teen Titans GOAL!'
     OR game_name = 'Tomb of Doom'
     OR game_name = 'Too Big to Fall'
     OR game_name = 'Xingo Mayhem'
    );
